name: Build and Deploy

on:
  push:
    branches:
      - dev
  workflow_dispatch:

env:
  NODE_VERSION: 24

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Security scan
        continue-on-error: true
        run: npm audit --audit-level=moderate

      - name: Prepare deployment
        run: |
          mkdir -p deploy
          cp minified/*.min.html deploy/
          for file in deploy/*.min.html; do
            mv "$file" "${file%.min.html}.html"
          done
          cp -r assets/ deploy/
          rm -rf deploy/assets/js/*.js
          cp assets/js/minified/*.min.js deploy/assets/js/
          cp manifest.json sitemap.xml robots.txt deploy/

      - uses: actions/configure-pages@v4

      - uses: actions/upload-pages-artifact@v4
        with:
          path: deploy

  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
