name: Lighthouse Local

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev
  workflow_dispatch:

env:
  NODE_VERSION: 24
  PHOTOGRAPHER_IDS: 243 930 82 527 925 195

permissions:
  contents: read
  pull-requests: write
  checks: write

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lighthouse:
    name: Lighthouse Local
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Start development server
        run: |
          npm run dev &
          for i in {1..30}; do
            if curl -s http://localhost:8080/ > /dev/null; then
              echo "Server ready"
              break
            fi
            sleep 2
          done

      - name: Generate test URLs
        id: urls
        run: |
          URLS="http://localhost:8080/"
          for id in ${{ env.PHOTOGRAPHER_IDS }}; do
            URLS="$URLS
          http://localhost:8080/photographer.html?id=$id"
          done
          echo "urls<<EOF" >> $GITHUB_OUTPUT
          echo "$URLS" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Run Lighthouse
        uses: treosh/lighthouse-ci-action@v11
        with:
          urls: ${{ steps.urls.outputs.urls }}
          uploadArtifacts: true
          temporaryPublicStorage: true
          runs: 3

      - name: Upload reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: lighthouse-local
          path: .lighthouseci
          retention-days: 30
