name: Release

on:
  push:
    tags:
      - 'v*'

env:
  NODE_VERSION: 24

permissions:
  contents: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: npm

      - name: Install dependencies
        run: npm ci --prefer-offline --no-audit

      - name: Validate code
        run: |
          npm run lint
          npm run format

      - name: Create release
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Release ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload assets
        run: gh release upload ${{ github.ref_name }} readme.md --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
