name: Release

on:
  push:
    tags:
      - "v*"

env:
  NODE_VERSION: 24

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: "npm"

      - name: Install
        run: npm ci --prefer-offline --no-audit || npm install --prefer-offline --no-audit

      - name: Build
        run: |
          npm run lint
          npm run format
          npm run minify

      - name: Create Release
        run: |
          gh release create ${{ github.ref_name }} \
            --title "Release ${{ github.ref_name }}" \
            --notes "Release ${{ github.ref_name }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload README
        run: gh release upload ${{ github.ref_name }} readme.md --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
